# 定义训练配置
config = {
    "data": {
        "total_samples": total_samples,
        "src_vocab_size": src_vocab_size,
        "tgt_vocab_size": tgt_vocab_size,
        "max_len": max_len,
        "batch_size": 32
    },
    "model": {
        "d_model": 256,
        "num_layers": 4,
        "num_heads": 4,
        "d_ff": 1024
    },
    "optimizer": {
        "type": "AdamW",
        "learning_rate": 5e-4,
        "betas": (0.9, 0.98),
        "eps": 1e-9
    },
    "scheduler": {
        "step_size": 5,
        "gamma": 0.8
    },
    "training": {
        "epochs": 80,
        "loss_function": "CrossEntropyLoss",
        "ignore_index": 0
    }
}
